### PR TITLE
Kickstart unit-test sub-project

### PR DESCRIPTION
**Pull request by Nagarian**

### CODE REVIEW

**Comment by Nagarian** [comment]
@CodeYan01

**Comment by CodeYan01** [comment]
Please add an empty line at the end of each line. If you try checking it with Git CLI with `git log -p` or `git diff`, it will warn with "No newline at end of file", for good reasons. See: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

**Comment by Nagarian** [comment]
> Please add an empty line at the end of each line. If you try checking it with Git CLI with `git log -p` or `git diff`, it will warn with "No newline at end of file", for good reasons. See: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

Thanks ! I've added an editorconfig file to help with it.

**Comment by CodeYan01** [comment]
Thanks!

**Pull request merged**
